export interface IWarehouseType {
    "ExportId"?: String,
    "ExportDate": number,
    "Content": String,
    "Status": String,
    "EmployeeId": String,
    "EmployeeName"?: String,
    "formatedExportDate"?: String,
    "ThesisName"?: String,
    "Instructor"?: String,
    "ResearchSubject"?: String,
    "LabName"?: String,
    "LabId"?: Number,
    "SessionId"?: Number,
    "RegisterGeneralId"?: Number,
    "TeacherName"?: String,
    "ClassId"?: String,
    "ClassName"?: String
    "DayOfWeek"?: Number,
    "StartTime"?: Number,
    "EndTime"?: Number,
    "LessonName"?: String,
    "SubjectName"?: String,
    "fortmatDateStudy"?: String,
    "DateStudy"?: number, 
}

export const dummyWarehouseData: IWarehouseType = {
    "ExportId": "",
    "ExportDate": Math.floor(Number(new Date()) / 1000),
    "Content": "",
    "Status": "",
    "EmployeeId": "",
    "EmployeeName": "",
    "formatedExportDate": "",
    "ThesisName": "",
    "Instructor": "",
    "ResearchSubject": "",
    "LabName": "",
    "LabId": -1,
    "SessionId": -1,
    "RegisterGeneralId": -1,
    "TeacherName": "",
    "ClassId": "",
    "ClassName": "",
    "DayOfWeek": -1,
    "StartTime": -1,
    "EndTime": -1,
    "LessonName": "",
    "SubjectName": "",
    "fortmatDateStudy": "",
    "DateStudy": Number(new Date())
}